language: java
sudo: required

install: /bin/true

jdk:
  - oraclejdk8

before_install:
  - gradle wrapper
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar

before_script:
  - wget https://services.gradle.org/distributions/gradle-4.4-bin.zip
  - unzip gradle-4.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.4
  - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml